language: node_js
node_js:
  - '15'
sudo: false
addons:
  apt:
    sources:
      - mongodb-upstart
      - mongodb-4.2-precise
    packages:
      - mongodb-org-server
      - mongodb-org-shell

before_script:
  - sleep 15

cache: yarn
branches:
  only:
    - main
env:
  global:
    - APP_NAM=teslog-travis
    - PORT=4400
    - MONGODB_URL=mongodb://localhost:27017/node-boilerplate
    - JWT_SECRET=thisisasamplesecret
    - JWT_ACCESS_EXPIRATION_MINUTES=30
    - JWT_REFRESH_EXPIRATION_DAYS=30
    - TESLA_OAUTH_V3_URL=https://auth.tesla.com/oauth2/v3
    - PUBLIC_URL=http://localhost
script:
  - yarn lint
  - yarn test
after_success: yarn coverage:coveralls
