language: node_js
node_js:
  - '15'
cache: yarn
branches:
  only:
    - main

env:
  global:
    - APP_NAME=teslog-travis
    - PORT=4400
    - MONGODB_URL=mongodb://localhost:27017/node-boilerplate
    - JWT_SECRET=thisisasamplesecret
    - JWT_ACCESS_EXPIRATION_MINUTES=30
    - JWT_REFRESH_EXPIRATION_DAYS=30
    - TESLA_OAUTH_V3_URL=https://auth.tesla.com/oauth2/v3
    - PUBLIC_URL=http://localhost

install:
  - wget http://fastdl.mongodb.org/linux/mongodb-linux-x86_64-4.2.8.tgz
  - tar xzf mongodb-linux-x86_64-4.2.8.tgz
  - ${PWD}/mongodb-linux-x86_64-4.2.8/bin/mongod --version

before_script:
  - mkdir ${PWD}/mongodb-linux-x86_64-4.2.8/data
  - ${PWD}/mongodb-linux-x86_64-4.2.8/bin/mongod --dbpath ${PWD}/mongodb-linux-x86_64-4.2.8/data --logpath ${PWD}/mongodb-linux-x86_64-4.2.8/mongodb.log --fork

script:
  - yarn lint
  - yarn test
after_success: yarn coverage:coveralls
