
version: '3.9'

services:
  api:
    image: devintyler2626/tesalate-api:latest
    build: .
    env_file:
      - .env
    environment:
      - MONGODB_URL=mongodb://mongodb:27017/tesla_db
    ports:
      - '4400:4400'
    depends_on:
      - mongodb
    volumes:
      - ./logs:/home/node/app/logs
    networks:
      - node-network

  mongodb:
    image: mongo:5.0.6
    ports:
      - '27021:27017'
    volumes:
      - dbdata:/data/db
    networks:
      - node-network

volumes:
  dbdata:

networks:
  node-network:
    driver: bridge