version: '3'

services:
  node-app:
    build: .
    image: node-app
    ports:
      - '4400:4400'
    # depends_on:
    #   - mongodb
    volumes:
      - .:/home/node/app
    networks:
      - node-network
    env_file:
      - .env


networks:
  node-network:
    driver: bridge
