name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  NODE_ENV: test
  PORT: 4400
  APP_NAME: tesalate-ci
  PUBLIC_URL: http://localhost
  MONGODB_URL: mongodb://localhost:27017/test
  JWT_SECRET: thisisasamplesecret
  JWT_ACCESS_EXPIRATION_MINUTES: 30
  JWT_REFRESH_EXPIRATION_DAYS: 30
  TESLA_OAUTH_V3_URL: https://auth.tesla.com/oauth2/v3
  TESLA_OWNERAPI_CLIENT_ID: '12345'
  TESLA_OWNERAPI_CLIENT_SECRET: '54321'
  ACCEPTED_CORS: '["http://localhost:4400"]'

jobs:
  ci:
    name: Building, linting, testing on node ${{ matrix.node }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: ['16.x', '17.4']
        os: [ubuntu-latest]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Use Node ${{ matrix.node }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}

      - name: Cache Deps
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install dependencies
        run: yarn

      - name: Lint
        run: yarn lint

      - name: Test
        run: yarn test -- --ci --coverage
