name: 'coverage'

on:
  pull_request:
    branches:
      - main

jobs:
  with:
    package-manager: yarn
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ArtiomTr/jest-coverage-report-action@v2
